[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "pytemplate"
version = "0.0.0"
requires-python = ">=3.10"

[project.optional-dependencies]
docs = [
    "pymdown-extensions",
    "mkdocstrings",
    "mkdocs-material",
    "mkdocstrings-python",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["pytemplate"]
